name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectKey: TAOUBI-123_archiva-parent      # Replace with your actual project key
          organization: TAOUBI       # Replace with your actual organization
          token: ${{ secrets.612d66b9a29caf8044f01965c7526be5ddb91e84 }}
 


